[package]
name = "firmware-manager-notify"
version = "0.1.3"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[features]
default = [ "fwupd", "system76" ]
system76 = []
fwupd = []

[build-dependencies]
fomat-macros = "0.3"

[dependencies]
notify-rust = { version = "4.5", default-features = false, features = ["dbus"] }
firmware-manager = { path = "../" }
i18n-embed = { version = "0.12.0", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.5.0"
rust-embed = "5.9.0"
once_cell = "1.7.2"
