[package]
name = "firmware-manager-notify"
version = "0.1.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[features]
default = [ "fwupd", "system76" ]
system76 = []
fwupd = []

[build-dependencies]
fomat-macros = "0.3"

[dependencies]
notify-rust = "4.5"
firmware-manager = { path = "../" }

